package main

import (
	"go_bedu/config"
	_ "go_bedu/docs" // docs is generated by Swag CLI, you have to import it.
	"go_bedu/routes"

	"github.com/labstack/echo/v4"
	echoSwagger "github.com/swaggo/echo-swagger"
)

// @title           bEDU Documentation API
// @version         1.0
// @termsOfService  http://swagger.io/terms/

// @contact.name   Dicoding Cycle 4 TEAM C23-M4058
// @contact.url    https://github.com/Capstone-Dicoding-Cycle-4-C23-M4058

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// ec2-54-66-56-235.ap-southeast-2.compute.amazonaws.com:8080
// localhost:8080

// @host     ec2-54-66-56-235.ap-southeast-2.compute.amazonaws.com:8080
// @BasePath  /api/v1

// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization

// @externalDocs.description  OpenAPI
// @externalDocs.url          https://swagger.io/resources/open-api/
func main() {
	db := config.InitDB()
	e := echo.New()

	routes.NewRoute(e, db)

	e.GET("/swagger/*", echoSwagger.WrapHandler)

	e.Logger.Fatal(e.Start(":8080"))
}
